In [2]:
#1.Why does this train-test split fail?
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
data = load_iris()
X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, random_state = 42)
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (120, 4)
X_test shape: (30, 4)


In [3]:
#2.
#fromsklearn import model_selection # This  is fine but not used
from sklearn import model_selection
from sklearn.tree import DecisionTreeClassifier

X = [[1, 2], [3, 4], [5, 6]]
y = [0, 1, 0]
model = DecisionTreeClassifier(max_depth=100)
model.fit(X, y)
score = model.fit(X, y)
print(score)

DecisionTreeClassifier(max_depth=100)


In [3]:
#3.
from sklearn.cluster import KMeans
import numpy as np

X = np.array([[1, 2], [3, 4], [5, 6]])

model = KMeans(n_clusters=3, n_init='auto')
model.fit(X)
print("Cluster centers:\n", model.cluster_centers_)

Cluster centers:
 [[5. 6.]
 [1. 2.]
 [3. 4.]]


In [26]:
#4.
import pandas as pd  

df = pd.DataFrame({'A': [1, 2, 3]})
print(df)

   A
0  1
1  2
2  3


In [7]:
#5.
from sklearn.tree import DecisionTreeClassifier  # Typo in 'DecisionTreeClassifier'
model = DecisionTreeClassifier()
model.fit(X, y)
predictions = model.predict(X)
print(predictions)



[0 1 0]


In [6]:
#6.from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(max_depth=3) 
model.fit(X, y)
predictions = model.predict(X)
print(predictions)


[0 1 0]


In [9]:
#7.
from sklearn.linear_model import LinearRegression

X = [[1], [2], [3], [4]]
y = [2, 4, 6, 8]

model = LinearRegression()
model.fit(X, y)

print(model.coef_)  # Incorrect attribute name


[2.]


In [9]:
#8.
from sklearn.neighbors import KNeighborsClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = [0, 1, 0]

model = KNeighborsClassifier(n_neighbors=1)  # Invalid value for n_neighbors
model.fit(X_train, y_train)
predictions = model.predict(X_train)
print(predictions)


[0 1 0]


In [12]:
#9.
import pandas as pd
from pandas import DataFrame 

df = pd.DataFrame({'A': [10, 20, 30], 'B': [1, 2, 3]})
print(df.loc[:,'A'])  # Incorrect: iloc requires integer indexes


0    10
1    20
2    30
Name: A, dtype: int64


In [8]:
#10.
from sklearn.ensemble import RandomForestClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = [0, 1, 0]

model = RandomForestClassifier()
model.fit(X_train, y_train)

probs = model.predict_proba([[1, 2]])  # Incorrect index
print(probs)


[[0.77 0.23]]
