In [2]:
#1.Debug the given code
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = {'Feature1': ['10', '20', '30'],  # 'Thirty' is not a valid number
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = df['Feature1'].astype(int)  # Error: Cannot convert 'Thirty' to int

print(df)


   Feature1  Feature2
0        10       5.5
1        20       6.7
2        30       8.9


In [3]:
#2.
import pandas as pd

data = {'A': [1, 2, None],  # Missing value
        'B': [4, None, 6]}  # Missing value

df = pd.DataFrame(data)
mean_value = df.mean()
df.fillna(mean_value)  # Error: fillna() does not modify in place

print(df)


     A    B
0  1.0  4.0
1  2.0  NaN
2  NaN  6.0


In [7]:
#3.
from sklearn.linear_model import LinearRegression
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

X = np.array([[1], [2], [3], [4], [5]])  # Error: X should be 2D
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)
print(model.predict([[6]])) # Predicting for a new value


[12.]


In [9]:
#4.
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([[10], [20], [30], [40], [50]])  # Error: Should be 2D

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)



[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [10]:
#5.Explanation: Labels must be 0 and 1 for classification.
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]  # Convert labels to numeric

model = LogisticRegression()
model.fit(X, y)

print(model.predict([[4, 5]]))


[1]


In [2]:
#6.Explanation: Convert categorical data into binary columns.
import pandas as pd
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})
encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(df[['Category']])
print(encoded)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [13]:
#6.Explanation: X and y must have the same number of samples.
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0, 1]  # Now y has the correct length
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print("X_train:", X_train)
print("y_train:", y_train)


X_train: [[7, 8], [5, 6], [3, 4]]
y_train: [1, 0, 1]


In [15]:
#7.A numerical prediction like [1] or [0].
#Explanation: Logistic Regression requires numeric labels, so we use LabelEncoder().
from sklearn.linear_model import LogisticRegression

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = [1, 0, 1]  # Error: LogisticRegression expects numerical labels

model = LogisticRegression()
model.fit(X_train, y_train)
print(model.predict([[4, 5]]))


[1]


In [16]:
#8.Replaced NaN with column mean using SimpleImputer to allow LinearRegression to train and predict correctly.import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

# Handling missing values by replacing NaN with the column mean
imputer = SimpleImputer(strategy="mean")
X_train_imputed = imputer.fit_transform(X_train)

# Train the model
model = LinearRegression()
model.fit(X_train_imputed, y_train)

# Make a prediction
prediction = model.predict([[3, 4]])
print("Predicted Output:", prediction)  

Predicted Output: [20.]


In [27]:
#9.
from sklearn.tree import DecisionTreeClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]  # Error: String labels not allowed

model = DecisionTreeClassifier()
model.fit(X_train, y_train)
print(model.predict([[4, 5]]))


['ham']


In [21]:
#10.Explanation:SVM is sensitive to feature scales. StandardScaler normalizes the features, improving model performance.from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
model = SVC()
model.fit(X_train_scaled, y_train)
X_test = [[1.5, 150], [2.5, 250]]
X_test_scaled = scaler.transform(X_test)
predictions = model.predict(X_test_scaled)
print(predictions)

[0 0]
